CREATE DATABASE IF NOT EXISTS askme;
USE askme;
CREATE TABLE users (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(60) NOT NULL,
    password CHAR(60) NOT NULL,
    photo VARCHAR(100) NOT NULL
);
